spring:
  datasource:
    url: jdbc:postgresql://ec2-3-217-72-66.compute-1.amazonaws.com:9999/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  address: 0.0.0.0
  port: 8080
